services:
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
        NEXT_PUBLIC_FIREBASE_API_KEY: ${FIREBASE_API_KEY}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${FIREBASE_APP_ID}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${FIREBASE_APP_ID}
    # Add performance optimizations
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    # Improve container networking
    dns:
      - 8.8.8.8
      - 8.8.4.4

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/credentials-google:/app/credentials-google:ro
      - ./backend:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials-google/moneymanager-f7891-firebase-adminsdk-fbsvc-341ad3a7c2.json
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here}
    # Add performance optimizations
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
